name: Tests CI

on:
  workflow_dispatch:
  push:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@vs
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Jar
        run: mvn test